# Generated by Django 3.0.7 on 2020-08-25 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish date')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='last modified date')),
                ('description', models.TextField(blank=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
