# Generated by Django 2.2.13 on 2020-08-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
