# Generated by Django 2.2.13 on 2020-09-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200829_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='https://raw.githubusercontent.com/iletthedawgsout/iletthedawgsout.com/master/black_lives_matter/black_lives_matter.md'),
            preserve_default=False,
        ),
    ]
